name: Update GitHub Profile Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: write

jobs:
  generate-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate profile stats
        uses: shinpr/github-profile-stats@main
        with:
          username: matiasperezsilva
          token: ${{ secrets.GITHUB_TOKEN }}
          profile: default
